### ISSUE TITLE
just say hi

### ISSUE THREAD

**Issue by ZenanH** [KeitaNakamura/Tesserae.jl#2]
Hi Keita,

I just noticed that we registered mpm-related packages at same day! What a coincidence!😊

At beginning, I was also try to provide a marco to do the scattering or gathering easily, however our aim is performance sensitive and I think it will be too far with my phd work... Anyway its good to find your package, I will have a try and also link to your repo in my package README.

Zenan

(I closed this issue)

**Comment by KeitaNakamura** [comment]
Hi @ZenanH, thank you for your kind words.

I totally get it—it's hard work to balance performance and readability. I’m not very familiar with GPU for now, but I’ll try it out in the future.

I appreciate you considering linking it in your README. I’ll be sure to check out your package too. Looking forward to seeing what you create.

Cheers,
Keita
