### ISSUE TITLE
Possible bug report about fluid simulation

### ISSUE THREAD

**Issue by Darkhell101** [KeitaNakamura/Tesserae.jl#4]
Dear Keita Nakamura,
I greatly appreciate your Julia library "Tesserae.jl." 
And I have run some of the listed tests, but encountered errors during the fluid simulation test. 
The related files are attached for your review. 
My julia version is 1.11.1.
System information: macos, ubuntu and windows11 (All give error information and erupt.)
If you could check them, it would be very helpful for other users of your library. 
Additionally, I would like to learn more about implicit formulation cases. 
Could you please provide additional example cases? 
Thank you for your time and assistance.
[file.zip](https://github.com/user-attachments/files/17811625/file.zip)

**Comment by KeitaNakamura** [comment]
Thank you for the report. However, I was unable to reproduce the errors. Could you please confirm the following?

* Is the simulation file exactly the same as the one used in the [original fluid simulation tutorial](https://keitanakamura.github.io/Tesserae.jl/stable/tutorials/dam_break/)?
* Do you still encounter the errors when using a smaller time step, such as `Δt = 1.0e-3`?

For the implicit formulation, please open a separate issue.

**Comment by Darkhell101** [comment]
Sorry to tell you, code still erupt at approximately 50% progress when Δt = 1.0e-3.
Could you send your running script of this example here?
My running file is copied from tutorial.
I want to check whether they are the same.

**Comment by Darkhell101** [comment]
https://github.com/user-attachments/assets/c71110c2-6d6b-49a7-99df-b1e2439193f4


https://github.com/user-attachments/assets/c607f791-82cc-4cce-9412-6b9eabb96af5

I have uploaded videos on both Windows and Linux. 
Linux displays error messages, whereas Windows does not. 
The progress bar reaches 100% rapidly, but no actual processing takes place.

**Comment by Darkhell101** [comment]
When viewed in ParaView, only the first three seconds of the animation play; the rest is blank.

**Comment by KeitaNakamura** [comment]
I reproduced the error on CI and am now checking the details.

**Comment by Darkhell101** [comment]
I found some information that might be helpful. 
First, changing the base parameters of the input doesn't alter the result. 
However, the parameters used in Newmark's method appear to differ from those recommended by Wikipedia. 
My understanding of integration algorithms is limited, and there could also be other issues at play.

**Comment by Darkhell101** [comment]
Great!
